<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Soc6graph</title>
        <meta name="description" content="Project to build visual graph from social network">
        <meta name="author" content="Dmytro Krushevskyi">
        <meta property="og:title" content="Soc6graph">
        <meta property="og:type" content="website">
        <meta property="og:description" content="Project to build visual graph from social network">
    </head>
    <body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous"
            src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v11.0&appId=${model.appId}&autoLogAppEvents=1"
            nonce="RJtkPLDm"></script>

    <div class="fb-login-button" data-width="" data-size="large" data-button-type="continue_with"
         data-layout="rounded" data-auto-logout-link="false" data-use-continue-as="true"></div>
    </body>
</html>